version: "3.8"
services:
  redis:
    image: redis:7.0.3
    container_name: word_of_wisdom_redis
    restart: unless-stopped
  client:
    build:
      dockerfile: client/Dockerfile
    container_name: word_of_wisdom_client
    environment:
      - SERVER_HOST=http://server:8081
    depends_on:
      - server
    restart: unless-stopped
  server:
    build:
      dockerfile: server/Dockerfile
    container_name: word_of_wisdom_server
    environment:
      - REDIS_HOST=redis:6379
    depends_on:
      - redis
    restart: unless-stopped